### ISSUE TITLE
Slow load time

### ISSUE THREAD

**Issue by delder818** [ludo/jquery-treetable#165] opened 2015-04-06 13:54 UTC
I have 6,500 records that are loaded on to the page and the time it takes to process this is 50 sec. Can anything be done to speed up the process? Is this table to big to use with this plug in? Are the nodes what slow this down?

**Comment by 57even** [comment] 2015-04-06 14:32
I have the same problem

**Comment by adambcaldwell** [comment] 2015-10-16 02:07
Issue #144 appears to provide a potential fix for this performance issue, I've been using it in my code and haven't noticed any issues thus far.

**Comment by ludo** [comment] 2016-03-07 10:43
Duplicate of #144.

**Closed by ludo** 2016-03-07 10:43 UTC
